title: Linguagem Potigol
description: Programação para todos
google_analytics: UA-66397531-1
show_downloads: false
theme: jekyll-theme-dinky
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-mentions
  - jekyll-paginate
  
plugins:
  - jemoji
